sudo: required

language: shell

services:
  - docker

script: docker build -t smccloud/monero-node .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push smccloud/monero-node:master
    fi
