sudo: required

language: shell

services:
  - docker

script: docker build -t smccloud/monero-node .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push smccloud/monero-node:latest
